src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(
        message: 'The email "{{ value }}" is not a valid email. Try again.',
    )]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Regex(
        pattern: '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/',
        message: 'Your password must contain : at least 1 uppercase letter, 1 lowercase letter, 1 number, at least 1 special character, at least 8 characters'
    )]
    private ?string $password = null;

    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your firstname must be at least {{ limit }} characters long',
        maxMessage: 'Your firstname cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $firstname = null;
    
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your lastname must be at least {{ limit }} characters long',
        maxMessage: 'Your lastname cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $lastname = null;

    #[Assert\Range(
        min: 1940,
        max: 2007,
        notInRangeMessage: 'Your birthyear must be between {{ min }} and {{ max }}',
    )]
    #[ORM\Column(nullable: true)]
    private ?int $birthyear = null;

    #[Assert\Length(
        min: 2,
        max: 255,
        minMessage: 'Your address must be at least {{ limit }} characters long',
        maxMessage: 'Your address cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your city must be at least {{ limit }} characters long',
        maxMessage: 'Your city cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $city = null;

    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your country must be at least {{ limit }} characters long',
        maxMessage: 'Your country cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = 'default.png';

    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your job must be at least {{ limit }} characters long',
        maxMessage: 'Your job cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $job = null;

    #[ORM\OneToMany(mappedBy: 'host', targetEntity: Room::class, orphanRemoval: true)]
    private Collection $rooms;

    #[ORM\OneToMany(mappedBy: 'traveler', targetEntity: Review::class, orphanRemoval: true)]
    private Collection $reviews;

    #[ORM\OneToMany(mappedBy: 'traveler', targetEntity: Booking::class, orphanRemoval: true)]
    private Collection $bookings;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'traveler', targetEntity: Favorite::class, orphanRemoval: true)]
    private Collection $favorites;

    public function __construct()
    {
        $this->rooms = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    // Fusion : Fistname + Lastname
    public function getFullname(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    // Current year minus birthyear to get age
    public function getAge(): ?int
    {
        return date('Y') - $this->birthyear;
    }
    
    public function getBirthyear(): ?int
    {
        return $this->birthyear;
    }

    public function setBirthyear(?int $birthyear): static
    {
        $this->birthyear = $birthyear;

        return $this;
    }


    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(?string $job): static
    {
        $this->job = $job;

        return $this;
    }

    /**
     * @return Collection<int, Room>
     */
    public function getRooms(): Collection
    {
        return $this->rooms;
    }

    public function addRoom(Room $room): static
    {
        if (!$this->rooms->contains($room)) {
            $this->rooms->add($room);
            $room->setHost($this);
        }

        return $this;
    }

    public function removeRoom(Room $room): static
    {
        if ($this->rooms->removeElement($room)) {
            // set the owning side to null (unless already changed)
            if ($room->getHost() === $this) {
                $room->setHost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setTraveler($this);
        }

        return $this;
    }

    public function removeReview(Review $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getTraveler() === $this) {
                $review->setTraveler(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): static
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setTraveler($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): static
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getTraveler() === $this) {
                $booking->setTraveler(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Entity\Room;
use App\Repository\RoomRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/r')] // prefix all room routes with /r
class RoomController extends AbstractController
{
    #[Route('/', name: 'app_room', methods: ['GET'])]
    public function index(
        RoomRepository $roomRepository,
        PaginatorInterface $paginator,
        Request $request,
    ): Response
    {
        $pagination = $paginator->paginate(
            $roomRepository->findAll(), // All rooms
            $request->query->getInt('page', 1), // Check page number
            12 // Items per page
        );

        return $this->render('room/index.html.twig', [
            'rooms' => $pagination,
            'hostRooms' => $roomRepository->findBy(
                ['host' => $this->getUser()]
                )
        ]);
    }

    #[Route('/{city}', name: 'app_room_city', methods: ['GET'])]
    public function city(
        RoomRepository $roomRepository,
        PaginatorInterface $paginator,
        Request $request,
    ): Response
    {
        $pagination = $paginator->paginate(
            $roomRepository->findBy(['city' => $request->attributes->get('city')]),
            $request->query->getInt('page', 1),
            12
        );

        return $this->render('room/index.html.twig', [
            'rooms' => $pagination,
            'hostRooms' => $roomRepository->findBy(
                ['host' => $this->getUser()]
            )
        ]);
    }

        #[Route('/details/{id}', name: 'room', methods: ['GET', 'POST'])]
    public function details(
        Room $room,
    ): Response
    {
        return $this->render('room/details.html.twig', [
            'room' => $room,
        ]);
    }
}

templates/room/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}What is your next sweet home?
{% endblock %}

{% block body %}
	<div class="p-5 mb-4 border-bottom border-2">
		<h1 class="">
			{{ room.title }}
		</h1>
	</div>

	<div class="container pb-5">
		<div class="row mb-3">
			<img src="{{ asset('/uploads/rooms/') }}{{ room.cover }}" alt="{{ room.title }}" class="img-fluid rounded-3">
		</div>
		<div class="d-flex gap-2 align-items-center mb-3">
			<div class="">
				<img src="{{ asset('/uploads/users/') }}{{ room.host.image }}" alt="{{ room.host.fullname }}" class="img-fluid rounded-pill" width="40">
			</div>
			<div class="">
				<p class="fs-3">Offer by {{ room.host.fullname }}</p>
			</div>
		</div>
		<div class="mb-5">
			<p class="fs-3">Description</p>
			<p class="fs-5">{{ room.description }}</p>
		</div>
		<div class="row mb-5">
			<div class="col-md-8 border-end">
				<p class="fs-3">Equipments</p>
				{% for item in room.equipment %}
					<p class="fs-5">• {{ item.name|capitalize }}</p>
				{% endfor %}
			</div>
			<div class="col-md-4">
				<p class="fs-3">Price</p>
				<p class="fs-5">{{ room.price }} €</p>
				<p class="fs-6">per night</p>
			</div>
		</div>
		<div class="row mb-5">
			<div class="border border-2 rounded-3 p-3">
				<p class="fs-3">Make a reservation</p>
				<form action={{ path('book_room', { room: room.id }) }} method="post">
					<div class="mb-3">
						<label for="checkin" class="form-label">Check-in</label>
						<input type="date" class="form-control" id="checkin" name="checkin" required>
					</div>
					<div class="mb-3">
						<label for="checkout" class="form-label">Check-out</label>
						<input type="date" class="form-control" id="checkout" name="checkout" required>
					</div>
					<div class="mb-3">
						<label for="guests" class="form-label">Guests</label>
						<input type="number" class="form-control" id="guests" name="guests" required>
					</div>
					{% if is_granted('ROLE_USER') %}
							<button type="submit" class="btn btn-custom btn-lg rounded-pill">Book</button>
						{% else %}
							<a href="{{ path('app_login') }}" class="btn btn-dark btn-lg rounded-pill">Login to book</a>
					{% endif %}
				</form>
			</div>
		</div>
	</div>
	{% block footer %}
		{% include 'components/footer-city.html.twig' %}
	{% endblock %}

{% endblock %}

templates/room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}What is your next sweet home?
{% endblock %}

{% block body %}
	<div class="p-5 mb-4 border-bottom border-2">
		<h1 class="">
			{% if is_granted('IS_AUTHENTICATED_FULLY') %}
				Welcome back
				<span class="text-main">{{ app.user.firstname }}</span>!
			{% else %}
				What is your next sweet home?
			{% endif %}
		</h1>
	</div>

	<div class="container">
		<div class="row">
			{% if  is_granted('ROLE_HOST') %}
				{% if hostRooms|length > 0 %} 
					{% for item in hostRooms %}
						{{ include('components/card.html.twig') }}
					{% endfor %}
				{% else %}
					<p class="text-center">You don't have any room yet.</p>
					<a href="#" class="btn btn-custom">Create your first room</a>
				{% endif %}
			{% else %}
				{% for item in rooms %}
					{{ include('components/card.html.twig') }}
				{% endfor %}
				
				<div class="d-flex justify-content-center my-5">
					{{ knp_pagination_render(rooms) }}
				</div>
			{% endif %}
		</div>
	</div>
	{% block footer %}
		{% include 'components/footer-city.html.twig' %}
	{% endblock %}

{% endblock %}