src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $number = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $check_in = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $check_out = null;

    #[ORM\Column]
    private ?int $occupants = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $traveler = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Review $review = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Room $room = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function getCheckIn(): ?\DateTimeInterface
    {
        return $this->check_in;
    }

    public function setCheckIn(\DateTimeInterface $check_in): static
    {
        $this->check_in = $check_in;

        return $this;
    }

    public function getCheckOut(): ?\DateTimeInterface
    {
        return $this->check_out;
    }

    public function setCheckOut(\DateTimeInterface $check_out): static
    {
        $this->check_out = $check_out;

        return $this;
    }

    public function getOccupants(): ?int
    {
        return $this->occupants;
    }

    public function setOccupants(int $occupants): static
    {
        $this->occupants = $occupants;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getTraveler(): ?User
    {
        return $this->traveler;
    }

    public function setTraveler(?User $traveler): static
    {
        $this->traveler = $traveler;

        return $this;
    }

    public function getReview(): ?Review
    {
        return $this->review;
    }

    public function setReview(?Review $review): static
    {
        $this->review = $review;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): static
    {
        $this->room = $room;

        return $this;
    }

    // Convert checkin date to string
    public function getCheckInString(): string
    {
        return $this->getCheckIn()->format('d/m/Y');
    }

    // Convert checkout date to string
    public function getCheckOutString(): string
    {
        return $this->getCheckOut()->format('d/m/Y');
    }

    // Get the number of days between checkin and checkout
    public function getDays(): int
    {
        $diff = $this->getCheckIn()->diff($this->getCheckOut());
        return $diff->days;
    }
    
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(
        message: 'The email "{{ value }}" is not a valid email. Try again.',
    )]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Regex(
        pattern: '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/',
        message: 'Your password must contain : at least 1 uppercase letter, 1 lowercase letter, 1 number, at least 1 special character, at least 8 characters'
    )]
    private ?string $password = null;

    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your firstname must be at least {{ limit }} characters long',
        maxMessage: 'Your firstname cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $firstname = null;
    
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your lastname must be at least {{ limit }} characters long',
        maxMessage: 'Your lastname cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $lastname = null;

    #[Assert\Range(
        min: 1940,
        max: 2007,
        notInRangeMessage: 'Your birthyear must be between {{ min }} and {{ max }}',
    )]
    #[ORM\Column(nullable: true)]
    private ?int $birthyear = null;

    #[Assert\Length(
        min: 2,
        max: 255,
        minMessage: 'Your address must be at least {{ limit }} characters long',
        maxMessage: 'Your address cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your city must be at least {{ limit }} characters long',
        maxMessage: 'Your city cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $city = null;

    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your country must be at least {{ limit }} characters long',
        maxMessage: 'Your country cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = 'default.png';

    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Your job must be at least {{ limit }} characters long',
        maxMessage: 'Your job cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $job = null;

    #[ORM\OneToMany(mappedBy: 'host', targetEntity: Room::class, orphanRemoval: true)]
    private Collection $rooms;

    #[ORM\OneToMany(mappedBy: 'traveler', targetEntity: Review::class, orphanRemoval: true)]
    private Collection $reviews;

    #[ORM\OneToMany(mappedBy: 'traveler', targetEntity: Booking::class, orphanRemoval: true)]
    private Collection $bookings;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'traveler', targetEntity: Favorite::class, orphanRemoval: true)]
    private Collection $favorites;

    public function __construct()
    {
        $this->rooms = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    // Fusion : Fistname + Lastname
    public function getFullname(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    // Current year minus birthyear to get age
    public function getAge(): ?int
    {
        return date('Y') - $this->birthyear;
    }
    
    public function getBirthyear(): ?int
    {
        return $this->birthyear;
    }

    public function setBirthyear(?int $birthyear): static
    {
        $this->birthyear = $birthyear;

        return $this;
    }


    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(?string $job): static
    {
        $this->job = $job;

        return $this;
    }

    /**
     * @return Collection<int, Room>
     */
    public function getRooms(): Collection
    {
        return $this->rooms;
    }

    public function addRoom(Room $room): static
    {
        if (!$this->rooms->contains($room)) {
            $this->rooms->add($room);
            $room->setHost($this);
        }

        return $this;
    }

    public function removeRoom(Room $room): static
    {
        if ($this->rooms->removeElement($room)) {
            // set the owning side to null (unless already changed)
            if ($room->getHost() === $this) {
                $room->setHost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setTraveler($this);
        }

        return $this;
    }

    public function removeReview(Review $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getTraveler() === $this) {
                $review->setTraveler(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): static
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setTraveler($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): static
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getTraveler() === $this) {
                $booking->setTraveler(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\ProfileType;
use App\Service\ProfileService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class UserController extends AbstractController
{
    #[Route('/complete-profile', name: 'complete_profile')]
    public function index(
        Request $request,
        ProfileService $profileService,
        EntityManagerInterface $em
    ): Response
    {
        $form = $this->createForm(ProfileType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $profileService->updateProfile($form, $this->getUser(), $em);
            
            $this->addFlash('success', 'Your profile has been updated');
            return $this->redirectToRoute('account');
        }
        return $this->render('user/profile.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * User account route for displaying it's own data on the app
     */
    #[Route('/account', name: 'account', methods: ['GET', 'POST'])]
    public function account(
        Request $request,
        EntityManagerInterface $em,
        ProfileService $profileService
    ): Response
    {
        if(!$this->getUser()->getFirstname()) {
            return $this->redirectToRoute('complete_profile');
        }

        $form = $this->createForm(ProfileType::class, $this->getUser());
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $profileService->updateProfile($form, $this->getUser(), $em);
            $this->addFlash('success', 'Your profile has been updated');
            return $this->redirectToRoute('account');
        }
        return $this->render('user/account.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/user/account.html.twig
{% extends 'base.html.twig' %}

{% block title %}My profile
{% endblock %}

{% block body %}
	<div class="container">
		<div class="row pb-5">
			<div class="col-lg-8 vstack gap-4 mt-5">
				<div class="card">
					<div class="card-body py-3">
						<div class="d-sm-flex align-items-start text-center text-sm-start">
							<div>
								<div class="avatar avatar-xxl profile-n-3 mb-3">
									<img class="avatar-img rounded-circle border border-white border-3" src="/uploads/users/{{ app.user.image }}" width="150">
								</div>
							</div>
							<div class="ms-sm-4 mt-sm-3">
								<h1 class="mb-0 h5">
									{{ app.user.firstname }}
									{{ app.user.lastname }}
									{% if app.user.isVerified %}
										<i class="bi bi-patch-check-fill text-primary"></i>
									{% endif %}
								</h1>
								<p>{{ app.user.email }}</p>
							</div>
							<div class="d-flex mt-3 justify-content-center ms-sm-auto">
								<button class="btn btn-danger-soft me-2" data-bs-toggle="modal" data-bs-target="#updateModal" type="button">
									<i class="bi bi-pencil-fill pe-1"></i>
									Update
								</button>
							</div>
						</div>
						<ul class="list-inline mb-0 text-center text-sm-start mt-3 mt-sm-0">
							<li class="list-inline-item">
								<i class="bi bi-briefcase me-1"></i>
								{{ app.user.job }}
							</li>
							<li class="list-inline-item">
								<i class="bi bi-geo-alt me-1"></i>
								Live in
								{{ app.user.city }}
							</li>
							<li class="list-inline-item">
								<i class="bi bi-cake2"></i>
								{{ app.user.age }}
								yo
							</li>
						</ul>
					</div>
				</div>
				<div
					class="row">
					{# Booking #}
					<div class="mb-4">
						<div class="card">
							<div class="card-header d-sm-flex justify-content-between align-items-center border-0">
								<h5 class="card-title">
									Your bookings
									<span class="badge bg-danger bg-opacity-10 text-danger">
										{{ app.user.bookings|length }}
									</span>
								</h5>
								<a class="btn btn-primary-soft btn-sm" href={{ path('bookings') }}>
									See more
								</a>
							</div>
							<div class="card-body position-relative pt-3">
								<div class="row g-3">
									{% for booking in app.user.bookings %}
										<div class="col-md-4 col-sm-12">
											<div class="card shadow-none text-center h-100">
												<div class="card-body p-2 pb-0">
													<p class="card-title border fw-bold rounded-pill mb-1 mt-1">
														{{ booking.room.title|slice(0, 15) }}...
													</p>
													<table class="table">
														<tbody>
															<tr>
																<th scope="row">Start at</th>
																<td>{{ booking.checkInString }}</td>
															</tr>
															<tr>
																<th scope="row">End at</th>
																<td>{{ booking.checkOutString }}</td>
															</tr>
														</tbody>
													</table>
												</div>
												<div class="card-footer p-2 border-0">
													<a href={{ path('booking_show', { booking: booking.id }) }} class="btn btn-sm btn-custom rounded-pill" data-bs-toggle="tooltip" data-bs-placement="top">
														<i class="bi bi-eye"></i>
														Check your booking
													</a>
												</div>
											</div>
										</div>
									{% endfor %}

								</div>
							</div>
							<!-- Card body END -->
						</div>
					</div>

					{# Favorites #}
					<div class="mb-4">
						<div class="card">
							<div class="card-header d-sm-flex justify-content-between align-items-center border-0">
								<h5 class="card-title">
									Your favorites
									<span class="badge bg-danger bg-opacity-10 text-danger">
										{{ app.user.favorites|length }}
									</span>
								</h5>
								<a class="btn btn-primary-soft btn-sm" href={{ path('favorites') }}>
									See more
								</a>
							</div>
							<div class="card-body position-relative pt-3">
								<div class="d-flex gap-3 overflow-x-scroll">
									{% for item in app.user.favorites %}
										<div class="col-md-4 col-sm-12">
											<div class="card shadow-none text-center h-100">
												<div class="card-body p-2">
													<img src="" class="img-fluid">
													{{ dump(item.id) }}
												</div>
												<div class="card-footer p-2 border-0">
													<button class="btn btn-sm btn-custom rounded-pill" data-bs-toggle="tooltip" data-bs-placement="top">
														<i class="bi bi-eye"></i>
														Check it
													</button>
													<button class="btn btn-sm btn-dark rounded-pill" data-bs-toggle="tooltip" data-bs-placement="top">
														<i class="bi bi-trash"></i>
														Remove
													</button>
												</div>
											</div>
										</div>

									{% endfor %}
								</div>
							</div>
							<!-- Card body END -->
						</div>
					</div>

					{# Rooms #}
					{% if is_granted('ROLE_HOST') %}
						<div class="mb-4">
							<div class="card">
								<div class="card-header d-sm-flex justify-content-between align-items-center border-0">
									<h5 class="card-title">
										Your offers
										<span class="badge bg-danger bg-opacity-10 text-danger">
											{{ app.user.rooms | length }}
										</span>
									</h5>
									<a class="btn btn-primary-soft btn-sm" href="#">
										See more
									</a>
								</div>
								<div class="card-body position-relative pt-3">
									<div class="row g-3">

										<div class="col-md-4 col-sm-12">
											<div class="card shadow-none text-center h-100">
												<div class="card-body p-2">
													<img src="https://placehold.co/250" class="img-fluid">
												</div>
												<div class="card-footer p-2 border-0">
													<button class="btn btn-sm btn-success rounded-pill" data-bs-toggle="tooltip" data-bs-placement="top">
														<i class="bi bi-pencil"></i>
														Manage
													</button>
												</div>
											</div>
										</div>

									</div>
								</div>
								<!-- Card body END -->
							</div>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="updateModalLabel">Update your informations</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					{{ form_start(form) }}
						{{ form_row(form.roles) }}
						{{ form_row(form.firstname) }}
						{{ form_row(form.lastname) }}
						{{ form_row(form.birthyear) }}
						{{ form_row(form.address) }}
						{{ form_row(form.city) }}
						{{ form_row(form.country) }}
						{{ form_row(form.job) }}
						{{ form_row(form.image) }}
						<button type="submit" class="btn btn-primary">Save changes</button>
					{{ form_end(form) }}
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>

	{% block footer %}
		{% include 'components/footer-city.html.twig' %}
	{% endblock %}
{% endblock %}

templates/user/dashboard.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/heroldpommier/Desktop/symfony_projects/bnb/src/Controller/UserController.php'|file_link(0) }}">src/Controller/UserController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/heroldpommier/Desktop/symfony_projects/bnb/templates/user/index.html.twig'|file_link(0) }}">templates/user/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/user/profile.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Complete your profile</title>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@900&family=Poppins:wght@300;500&display=swap" rel="stylesheet">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
		<link rel="stylesheet" href="">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous" defer></script>
	</head>
	<body class="bg-body-tertiary">
		<div class="vh-100 d-flex flex-column align-items-center justify-content-center">
			<img src="{{asset('/images/icon.svg')}}" alt="BnB logo" width="200">
			<h1 class="text-center my-4">Complete your profile</h1>
			<p>
				Just a few more steps to complete your profile and start using BnB.
			</p>
			{{ form_start(form, {
				'attr': {
					'class': 'col-md-6 col-sm-10'}
				}
			) }}
			{{ form_errors(form) }}
			<div class="form-floating mb-2">
				{{ form_widget(form.roles, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.roles
						}) }}
				<label for="floatingInput">What kind of user are you?</label>
			</div>
			<div class="form-floating mb-2">
				{{ form_widget(form.firstname, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.firstname
						}) }}
				<label for="floatingInput">Your firstname</label>
			</div>
			<div class="form-floating mb-2">
				{{ form_widget(form.lastname, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.lastname
						}) }}
				<label for="floatingInput">Your lastname</label>
			</div>
			<div class="form-floating mb-2">
				{{ form_widget(form.birthyear, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.birthyear
						}) }}
				<label for="floatingInput">Your birth Year</label>
			</div>
			<div class="form-floating mb-2">
				{{ form_widget(form.address, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.address
						}) }}
				<label for="floatingInput">Your billing address</label>
			</div>
			<div class="form-floating mb-2">
				{{ form_widget(form.city, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.city
						}) }}
				<label for="floatingInput">Your city</label>
			</div>
			<div class="form-floating mb-2">
				{{ form_widget(form.country, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.country
						}) }}
				<label for="floatingInput">Your country</label>
			</div>
			<div class="form-floating mb-2">
				{{ form_widget(form.job, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.job
						}) }}
				<label for="floatingInput">Your job</label>
			</div>
			<div class="input-group mb-2">
				{{ form_widget(form.image, {
							attr: {
								class: 'form-control',
							},
							'value': app.user.image
						}) }}
				<label class="input-group-text">
					<i class="bi bi-file-image"></i>
				</label>
			</div>
			<button type="submit" class="mt-2 btn btn-dark btn-lg rounded-pill">
				Save
			</button>
			{{ form_end(form) }}
		</div>
</html></body></html>